steps:
- name: "gcr.io/cloud_builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/web_server:$_TAG",
      "--build-arg", "project_id=$PROJECT_ID", "."]
images: ["gcr.io/$PROJECT_ID/web_server:$_TAG"]
